networks:
  goldenpath_network:
    name: goldenpath_network
    external: false

services:
  monitoring_otel:
    container_name: monitoring_otel
    image: grafana/otel-lgtm@sha256:09d8c3ce4f3a5f2f5b1ef7a3cc526a7e03b608aeef3ea1c67c912df43b2690c9
    networks:
      - goldenpath_network
    restart: always
    profiles:
      - monitoring
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "4000:3000" # Grafana UI

  alloy:
    container_name: monitoring_alloy
    image: grafana/alloy:latest@sha256:e849f170152aff2015427908463a08c48416abade66302cd880379609058042b
    profiles:
      - monitoring
    depends_on:
      - monitoring_otel
    networks:
      - goldenpath_network
    ports:
      - "12345:12347" # Faro receiver /collect endpoint
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
